### ISSUE TITLE
ODE manual gradients

### ISSUE THREAD

**Issue by OriolAbril** [pymc-devs/pymc-examples#106]
File: https://github.com/pymc-devs/pymc-examples/blob/main/examples/ode_models/ODE_with_manual_gradients.ipynb
Reviewers:

> The sections below may still be pending. If so, the issue is still available, it simply doesn't
> have specific guidance yet. Please refer to [this overview of updates](https://github.com/pymc-devs/pymc-examples/wiki/Notebook-updates-overview)

## Known changes needed
Changes listed in this section should all be done at some point in order to get this
notebook to a "Best Practices" state. However, these are probably not enough!
Make sure to thoroughly review the notebook and search for other updates.

### General updates
*

### ArviZ related
*

## Changes for discussion
Changes listed in this section are up for discussion, these are ideas on how to improve
the notebook but may not have a clear implementation, or fix some know issue only partially.

### General updates
*

### ArviZ related
*

**Comment by gbrunkhorst** [comment]
Hi @OriolAbril  I would be interested in helping with the ODE tutorial(s).  To get oriented, I did a little inventory of the ODE tutorials.  There are 5 different ODEs models spread across 5 different notebooks.
1. [ODE manual gradients (notebook for this open issue)](https://www.pymc.io/projects/examples/en/latest/ode_models/ODE_with_manual_gradients.html) : Lotka Volterra (Hudson's Bay Company Data), Fitzhugh-Nagumo (SMC example - no gradients)
2. [pymc3.ode Shapes and Benchmarking](https://www.pymc.io/projects/examples/en/latest/ode_models/ODE_API_shapes_and_benchmarking.html): "Simple enzymatic reaction"
3. [GSoC 2019: pymc.ode API](https://www.pymc.io/projects/examples/en/latest/ode_models/ODE_API_introduction.html): free-fall equation, SIR model
4. [Approximate Bayesian Computation](https://www.pymc.io/projects/examples/en/latest/samplers/SMC-ABC_Lotka-Volterra_example.html): another Lotka Volterra (simulated data)
5. [sunode docs](https://github.com/pymc-devs/sunode): have another pymc-based Lotka Volterra model using the Hudson's Bay Company data.

Stylistically, they vary widely as well, e.g., the first notebook reads like a long first-person blog article and the second notebook lacks explanation.  So my question is how much reorganizing do you want to do at this point?  I have some ideas and time to help, but I don't want to rewrite something if my task is mainly related to formatting.

**Comment by OriolAbril** [comment]
Hi @gbrunkhorst, sorry for the slow reply.

I would personally try to reorganize and split the content into notebooks with a smallish scope trying to follow https://diataxis.fr/, i.e. one notebook would be how-to and show how to solve an ode model with pymc (but not go into pymc ode module vs sunode nor about explaining the architecture of the ode module...) another one would be an explanation about the alternatives and how they depend on the types of models. (keep in mind I only a very sporadic user of pymc+odes so the specifics might not make sense, I am only trying to communicate the structure/scope idea).

I am also not sure what is the current state of the existing notebooks, are they all still useful? do they require a lot of work to get them updated? It would also be great to know any ideas you might already have too, are there things outdated or confusing that need to be addressed?

I am also tagging @aseyboldt and @armavica who will probably be able to help more than me

**Comment by gbrunkhorst** [comment]
Thanks, @OriolAbril, if you are good with reorganizing and splitting, here is a proposal:  

One notebook would take an ODE, Lotka Volterra, and solve it multiple ways:  1. non-Bayesian (scipy), 2. Bayesian with gradients (HMC): a. pymc.ode, b. manual gradients, c. sunode, and 3. Bayesian without gradients: a. SMC, b. MH?  This would help the future reader to know the options and why.  This would be a long notebook.  

Then the other models that are currently in the documentation could be presented as stand-alone notebook examples, titled something like this: "ODE Example: Equation ___ Solved Using ___".  These would be short.     

I'm thinking that the code and text can be pulled largely from the existing notebooks, although we would lose a bunch of text from [this one](https://www.pymc.io/projects/examples/en/latest/ode_models/ODE_with_manual_gradients.html). 

Let me know your thoughts.

**Comment by gbrunkhorst** [comment]
Sorry @OriolAbril : I'm following the [tutorial](https://pymc-data-umbrella.xyz/en/latest/sprint/tutorials/docstring_tutorial.html#docstring-tutorial) to get set up, but I'm getting an error with the environment at the conda prompt in Windows.  Code and error message below.  Let me know if you have thoughts.    

Code
`conda env create -f https://github.com/pymc-devs/pymc/blob/main/conda-envs/windows-environment-dev.yml`


Error message
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
>     Traceback (most recent call last):
>       File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
>         return func(*args, **kwargs)
>       File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
>         exit_code = getattr(module, func_name)(args, parser)
>       File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 81, in execute
>         spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
>       File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 43, in detect
>         if spec.can_handle():
>       File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
>         self._environment = env.from_file(self.filename)
>       File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 165, in from_file
>         return from_yaml(yamlstr, filename=filename)
>       File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 142, in from_yaml
>         data = yaml_safe_load(yamlstr)
>       File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 67, in yaml_safe_load
>         return yaml.safe_load(string, version="1.2")
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 980, in safe_load
>         return load(stream, SafeLoader, version)
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 935, in load
>         return loader._constructor.get_single_data()
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 109, in get_single_data
>         node = self.composer.get_single_node()
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 78, in get_single_node
>         document = self.compose_document()
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 104, in compose_document
>         self.parser.get_event()
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 163, in get_event
>         self.current_event = self.state()
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 239, in parse_document_end
>         token = self.scanner.peek_token()
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 182, in peek_token
>         self.fetch_more_tokens()
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 282, in fetch_more_tokens
>         return self.fetch_value()
>       File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 651, in fetch_value
>         raise ScannerError(
>     ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
>       in "<unicode string>", line 28, column 66:
>          ... le" content="{&quot;groups&quot;: [], &quot;environmentKey&quot; ...
>                                              ^ (line: 28)

**Comment by gbrunkhorst** [comment]
@OriolAbril - I wrote a new notebook and sent a pull request!  Hopefully I did everything right!  let me know if there are any questions or concerns.    

I basically wrote the notebook that I wish I had available to me when I was trying to use Bayesian inference with numerical scripts.  I learned that the pymc.ODE module basically replicates the approach in the ODE manual gradients notebook, so I think the ODE manual gradients notebook goes away (although we could salvage the second ODE in the notebook as a stand-alone short example, after this one is finalized).

**Comment by OriolAbril** [comment]
Thank you so much! Sorry about the slow replies. I'll review the PR as soon as possible.
